"""modificado estrutura do approved_card

Revision ID: 0e851ae96926
Revises: 6832b5dc9e25
Create Date: 2024-03-12 02:27:58.554771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e851ae96926'
down_revision = '6832b5dc9e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_de_pessoa', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('nome_raz_o_social', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('e_mail', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('valor_total_da_compra', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('qual_tipo_de_im_vel', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('endere_o', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('n_mero', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('qual_valor_do_im_vel', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('qual_o_valor_do_empr_stimo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('indica_o', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('assessor_respons_vel', sa.String(length=100), nullable=True))
        batch_op.alter_column('estado_civil',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('prazo_pagamento',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('nome')
        batch_op.drop_column('status')
        batch_op.drop_column('valor_emprestimo')
        batch_op.drop_column('renda_mensal')
        batch_op.drop_column('tipo_pessoa')
        batch_op.drop_column('endereco')
        batch_op.drop_column('valor_propriedade')
        batch_op.drop_column('email')
        batch_op.drop_column('tipo_terreno')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('numero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_terreno', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_propriedade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('endereco', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_pessoa', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('renda_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('valor_emprestimo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.alter_column('prazo_pagamento',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('estado_civil',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('assessor_respons_vel')
        batch_op.drop_column('indica_o')
        batch_op.drop_column('qual_o_valor_do_empr_stimo')
        batch_op.drop_column('qual_valor_do_im_vel')
        batch_op.drop_column('n_mero')
        batch_op.drop_column('endere_o')
        batch_op.drop_column('qual_tipo_de_im_vel')
        batch_op.drop_column('valor_total_da_compra')
        batch_op.drop_column('e_mail')
        batch_op.drop_column('cpf')
        batch_op.drop_column('nome_raz_o_social')
        batch_op.drop_column('tipo_de_pessoa')

    # ### end Alembic commands ###
