"""alterado tamanho do campo cpf

Revision ID: 488f8449328e
Revises: efb4ff0c9bd2
Create Date: 2024-03-12 05:03:52.148871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488f8449328e'
down_revision = 'efb4ff0c9bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=True)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
