"""alterado id's incrementados para id's aleatorios

Revision ID: fa20f3df3aa1
Revises: 7ef741be71c9
Create Date: 2024-05-16 03:56:07.231157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa20f3df3aa1'
down_revision = '7ef741be71c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer, type_=sa.String(length=36), existing_nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer, type_=sa.String(length=36), existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.Integer, type_=sa.String(length=36), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.String(length=36), type_=sa.Integer, existing_nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.String(length=36), type_=sa.Integer, existing_nullable=False)

    with op.batch_alter_table('approved_card', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.String(length=36), type_=sa.Integer, existing_nullable=False)

    # ### end Alembic commands ###
